name: ESLint Auto-fix and Check

on:
  pull_request:
    branches:
      - main
      - 'release-*'
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - 'release-*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:

      # 0. Stop infinite loop
      - name: Check if commit is made by bot
        if: github.actor == 'github-actions[bot]'
        run: echo "Commit made by bot. Exiting workflow." && exit 0

      # 1. Checkout the repository with credentials persisted for push
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      # 2. Set up pnpm
      - uses: pnpm/action-setup@v4
        with:
          version: 10

      # 2.1. Cache pnpm store
      - name: Get pnpm store
        id: pnpm-cache-store
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      # 2.2. Cache pnpm store
      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache-store.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # 3. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      # 4. Install dependencies using pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 5. Run ESLint with --fix and check for errors in one step
      - name: Run ESLint --fix and Check for Errors
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Disable immediate exit on error
          set +e

          # Run ESLint with --fix

          pnpm run lint:fix
          FIX_EXIT_CODE=$?

          # Configure Git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Commit and push fixes if any changes were made
          if [[ `git status --porcelain` ]]; then
            git add .
            git commit -m "chore: Apply ESLint fixes [skip ci]" --no-verify
            git push origin HEAD:${{ github.head_ref }}
          fi

          if [ $FIX_EXIT_CODE -ne 0 ]; then
            echo "ESLint checks failed. FIX_EXIT_CODE=$FIX_EXIT_CODE"
            exit 1
          fi
